In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import shutil
import os

In [2]:
df = pd.read_csv('../data/meta.txt',sep=';')

In [3]:
df.head()

file_name                                      file_path  ready  \
0   photo_98089.jpg   ../data/bug_guide/plecoptera/photo_98089.jpg      1   
1  photo_255771.jpg  ../data/bug_guide/plecoptera/photo_255771.jpg      1   
2  photo_255991.jpg  ../data/bug_guide/plecoptera/photo_255991.jpg      0   
3  photo_258045.jpg  ../data/bug_guide/plecoptera/photo_258045.jpg      1   
4  photo_654326.jpg  ../data/bug_guide/plecoptera/photo_654326.jpg      0   

   back_view  side_view  ruler  hand_nature  m_adult  contrast  \
0          0          0      0            0        0         0   
1          0          0      0            0        0         0   
2          0          0      0            0        0         0   
3          0          0      0            0        0         0   
4          0          0      0            1        0         0   

   noisy_background  partial                    order  \
0                 0        0  Stoneflies (Plecoptera)   
1                 0        0  Stoneflies (Plecoptera)   
2                 1        0  Stoneflies (Plecoptera)   
3                 0        0  Stoneflies (Plecoptera)   
4                 1        0  Stoneflies (Plecoptera)   

                                 family  
0  Winter Stoneflies (Taeniopterygidae)  
1  Winter Stoneflies (Taeniopterygidae)  
2  Winter Stoneflies (Taeniopterygidae)  
3   Small Winter Stoneflies (Capniidae)  
4        Spring Stoneflies (Nemouridae)

In [4]:
df.shape

(5603, 13)

In [5]:
order_dict = {'Stoneflies (Plecoptera)':'Plecoptera','Plecoptera (Stoneflies)':'Plecoptera',
'Mayflies (Ephemeroptera)':'Ephemeroptera','Ephemeroptera (Mayflies)':'Ephemeroptera',
'Caddisflies (Trichoptera)':'Trichoptera','Trichoptera (Caddisflies)':'Trichoptera',
'Diptera (True Flies)':'Diptera','Flies (Diptera)':'Diptera'}
order_list = []
for i in df.order:
    order_list.append(order_dict[i])
df.order = order_list

In [7]:
np.where(df.order=='Ephemeroptera')[0].shape

(2653,)

In [6]:
df2 = df.iloc[np.where(df.order=='Ephemeroptera')[0]]

In [7]:
df2.family.unique()

array(['Common Burrower Mayflies (Ephemeridae)',
       'Spiny Crawler Mayflies (Ephemerellidae)',
       'Flatheaded Mayflies (Heptageniidae)',
       'Small Minnow Mayflies (Baetidae)',
       'Small Squaregilled Mayflies (Caenidae)',
       'Little Stout Crawler Mayflies (Leptohyphidae)',
       'Pale Burrower Mayflies (Polymitarcyidae)',
       'Riverbed Burrower Mayflies (Palingeniidae)',
       'Hacklegilled Burrower Mayflies (Potamanthidae)',
       'Armored Mayflies (Baetiscidae)',
       'Pronggilled Mayflies (Leptophlebiidae)',
       'Ephemeridae (Hexes and Big Drakes)',
       'Ephemerellidae (Hendricksons, Sulphurs, PMDs, BWOs)',
       'Baetidae (Blue-Winged Olives)',
       'Heptageniidae (March Browns, Cahills, Quill Gordons)',
       'Baetiscidae (Armored Mayflies)', 'Isonychiidae (Slate Drakes)',
       'Ameletidae (Brown Duns)',
       'Leptophlebiidae (Blue Quills and Mahogany Duns)',
       'Siphlonuridae (Gray Drakes)', 'Leptohyphidae (Tricos)', nan,
       'Metre

In [9]:
df2 = df.iloc[np.where(df.order=='Plecoptera')[0]]

In [10]:
df2.family.unique()

array(['Winter Stoneflies (Taeniopterygidae)',
       'Small Winter Stoneflies (Capniidae)',
       'Spring Stoneflies (Nemouridae)',
       'Rolled-winged Stoneflies (Leuctridae)',
       'Green Stoneflies (Chloroperlidae)', 'Common Stoneflies (Perlidae)',
       'Perlodid Stoneflies (Perlodidae)',
       'Giant Stoneflies (Pteronarcyidae)',
       'Roach-like Stoneflies (Peltoperlidae)', 'None',
       'Pteronarcyidae (Salmonflies)',
       'Perlodidae (Springflies & Yellow Stones)',
       'Perlidae (Golden Stones)', 'Chloroperlidae (Sallflies)',
       'Peltoperlidae (Roachflies)', 'Taeniopterygidae (Willowflies)',
       'Capniidae (Snowflies)', 'Nemouridae (Forestflies)',
       'Leuctridae (Needleflies)', nan], dtype=object)

In [11]:
df2 = df.iloc[np.where(df.order=='Trichoptera')[0]]

In [12]:
df2.family.unique()

array(['Fingernet Caddisflies (Philopotamidae)',
       'Netspinning Caddisflies (Hydropsychidae)',
       'Long-horned Caddisflies (Leptoceridae)',
       'Giant Casemakers (Phryganeidae)',
       'Microcaddisflies (Hydroptilidae)', 'Calamoceratidae',
       'Mortarjoint Casemakers (Odontoceridae)',
       'Northern Caddisflies (Limnephilidae)', 'Thremmatidae',
       'Stonecase Caddisflies (Uenoidae)',
       'Humpless Casemaker Caddisflies (Brachycentridae)',
       'Bizarre Caddisflies (Lepidostomatidae)', 'None',
       'Tube Maker Caddisflies (Polycentropodidae)', 'Dipseudopsidae',
       'Net Tube Caddisflies (Psychomyiidae)',
       'Little Black Caddisflies (Glossosomatidae)',
       'Free-living Caddisflies (Rhyacophilidae)',
       'Hood Casemakers (Molannidae)',
       'Snail-case Caddisflies (Helicopsychidae)',
       'Bushtailed Caddisflies (Sericostomatidae)',
       'Early Smoky Wing Sedges (Apataniidae)', 'Goeridae',
       'Rhyacophilidae (Green Sedges)',
       'Limn

In [15]:
df2 = df.iloc[np.where(df.order=='Diptera')[0]]
df2.family.unique()

array(['Bee Flies (Bombyliidae)', 'Mosquitoes (Culicidae)',
       'Hilarimorphidae', 'Mountain Midges (Deuterophlebiidae)',
       'Canacidae', 'Dryomyzidae', 'Biting Midges (Ceratopogonidae)',
       'Ditomyiidae', 'Heterocheilidae', 'Bat Flies (Streblidae)',
       'Periscelididae', 'Curtonotidae', 'Pachyneuridae',
       'Phantom Crane Flies (Ptychopteridae)',
       'Large Crane Flies (Tipulidae)',
       'Moth Flies and Sand Flies (Psychodidae)', 'Midges (Chironomidae)',
       'March Flies (Bibionidae)',
       'Gall Midges and Wood Midges (Cecidomyiidae)',
       'Winter Crane Flies (Trichoceridae)', 'Nymphomyiidae',
       'Limoniid Crane Flies (Limoniidae)',
       'Predatory Fungus Gnats (Keroplatidae)',
       'Net-winged Midges (Blephariceridae)', 'Meniscus Midges (Dixidae)',
       'Cylindrotomid Crane Flies (Cylindrotomidae)',
       'Hairy-eyed Crane Flies (Pediciidae)',
       'Fungus Gnats (Mycetophilidae)', 'Wood Gnats (Anisopodidae)',
       'Axymyiidae', 'Canthylos

In [18]:
df2 = df.iloc[np.where(df.order!='Diptera')[0]]
df2.shape

(4507, 13)

In [28]:
family_dict = {
                'Goeridae':'Goeridae',
                'Dipseudopsidae':'Dipseudopsidae',
                'Calamoceratidae':'Calamoceratidae',
                'Thremmatidae':'Thremmatidae',
                'Fingernet Caddisflies (Philopotamidae)':'Philopotamidae',
                'Philopotamidae':'Philopotamidae',
                'Netspinning Caddisflies (Hydropsychidae)':'Hydropsychidae',
                'Hydropsychidae':'Hydropsychidae',
                'Long-horned Caddisflies (Leptoceridae)':'Leptoceridae',
                'Leptoceridae':'Leptoceridae',
                'Giant Casemakers (Phryganeidae)':'Phryganeidae',
                'Phryganeidae':'Phryganeidae',
                'Microcaddisflies (Hydroptilidae)':'Hydroptilidae',
                'Hydroptilidae (Microcaddisflies)':'Hydroptilidae',
                'Mortarjoint Casemakers (Odontoceridae)':'Odontoceridae',
                'Odontoceridae':'Odontoceridae',
                'Northern Caddisflies (Limnephilidae)':'Limnephilidae',
                'Limnephilidae (Northern Caddisflies)':'Limnephilidae',
                'Stonecase Caddisflies (Uenoidae)':'Uenoidae',
                'Uenoidae':'Uenoidae',
                'Humpless Casemaker Caddisflies (Brachycentridae)':'Brachycentridae',
                'Brachycentridae (Apple Caddis and Grannoms)':'Brachycentridae',
                'Bizarre Caddisflies (Lepidostomatidae)':'Lepidostomatidae',
                'Lepidostomatidae (Little Brown Sedges)':'Lepidostomatidae',
                'Tube Maker Caddisflies (Polycentropodidae)':'Polycentropodidae',
                'Polycentropodidae':'Polycentropodidae',
                'Net Tube Caddisflies (Psychomyiidae)':'Psychomyiidae',
                'Little Black Caddisflies (Glossosomatidae)':'Glossosomatidae',
                'Glossosomatidae (Saddle-case Makers)':'Glossosomatidae',
                'Free-living Caddisflies (Rhyacophilidae)':'Rhyacophilidae',
                'Rhyacophilidae (Green Sedges)':'Rhyacophilidae',
                'Hood Casemakers (Molannidae)':'Molannidae',
                'Molannidae':'Molannidae',
                'Snail-case Caddisflies (Helicopsychidae)':'Helicopsychidae',
                'Bushtailed Caddisflies (Sericostomatidae)':'Sericostomatidae',
                'Early Smoky Wing Sedges (Apataniidae)':'Apataniidae',
                'Apataniidae (Early Smoky Wing Sedges)':'Apanatiidae',
                'Common Burrower Mayflies (Ephemeridae)':'Ephemeridae',
                'Ephemeridae (Hexes and Big Drakes)':'Ephemeridae',
                'Spiny Crawler Mayflies (Ephemerellidae)':'Ephemerellidae',
                'Ephemerellidae (Hendricksons, Sulphurs, PMDs, BWOs)':'Ephemerellidae',
                'Flatheaded Mayflies (Heptageniidae)':'Heptageniidae',
                'Heptageniidae (March Browns, Cahills, Quill Gordons)':'Heptageniidae',
                'Small Minnow Mayflies (Baetidae)':'Baetidae',
                'Baetidae (Blue-Winged Olives)':'Baetidae',
                'Small Squaregilled Mayflies (Caenidae)':'Caenidae',
                "Caenidae (Angler's Curses)":'Caenidae',
                'Little Stout Crawler Mayflies (Leptohyphidae)':'Leptohyphidae',
                'Leptophlebiidae (Blue Quills and Mahogany Duns)':'Leptohyphidae',
                'Pale Burrower Mayflies (Polymitarcyidae)':'Polymitarcyidae',
                'Armored Mayflies (Baetiscidae)':'Baetiscidae',
                'Baetiscidae (Armored Mayflies)':'Baetiscidae',
                'Riverbed Burrower Mayflies (Palingeniidae)':'Palingeniidae',
                'Hacklegilled Burrower Mayflies (Potamanthidae)':'Potamanthidae',
                'Pronggilled Mayflies (Leptophlebiidae)':'Leptophlebiidae',
                'Isonychiidae (Slate Drakes)':'Isonychiidae',
                'Ameletidae (Brown Duns)':'Ameletidae',
                'Siphlonuridae (Gray Drakes)':'Siphlonuridae',
                'Metretopodidae (Pseudo-Gray Drakes)':'Metretopodidae',
                'Neoephemeridae':'Neoephemeridae',
                'Leptohyphidae (Tricos)':'Leptohyphidae',
                'Winter Stoneflies (Taeniopterygidae)':'Taeniopterygidae',
                'Taeniopterygidae (Willowflies)':'Taeniopterygidae',
                'Small Winter Stoneflies (Capniidae)':'Capniidae',
                'Capniidae (Snowflies)':'Capniidae',
                'Spring Stoneflies (Nemouridae)':'Nemouridae',
                'Nemouridae (Forestflies)':'Nemouridae',
                'Rolled-winged Stoneflies (Leuctridae)':'Leuctridae',
                'Leuctridae (Needleflies)':'Leuctridae',
                'Green Stoneflies (Chloroperlidae)':'Chloroperlidae',
                'Chloroperlidae (Sallflies)':'Chloroperlidae',
                'Common Stoneflies (Perlidae)':'Perlidae',
                'Perlidae (Golden Stones)':'Perlidae',
                'Perlodid Stoneflies (Perlodidae)':'Perlodidae',
                'Perlodidae (Springflies & Yellow Stones)':'Perlodidae',
                'Giant Stoneflies (Pteronarcyidae)':'Pteronarcyidae',
                'Pteronarcyidae (Salmonflies)':'Pteronarcyidae',
                'Roach-like Stoneflies (Peltoperlidae)':'Peltoperlidae',
                'Peltoperlidae (Roachflies)':'Peltoperlidae',
                'nan':'nan',
                'None':'None'
              }

In [30]:
family_subset = [family_dict[i] for i in df2.family.astype('str')]

In [31]:
df2.family = family_subset

/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pandas/core/generic.py:3643: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [35]:
family_counts = np.unique(df2.family,return_counts=True)
a = np.flip(np.argsort(family_counts[1]),axis=0)
print(family_counts[0][a],family_counts[1][a])

['Ephemerellidae' 'Heptageniidae' 'Ephemeridae' 'Baetidae' 'Leptohyphidae'
 'Limnephilidae' 'Perlidae' 'Perlodidae' 'Hydropsychidae' 'Baetiscidae'
 'Chloroperlidae' 'Nemouridae' 'Leptoceridae' 'Taeniopterygidae'
 'Isonychiidae' 'Rhyacophilidae' 'Pteronarcyidae' 'Capniidae' 'Caenidae'
 'Philopotamidae' 'Peltoperlidae' 'Brachycentridae' 'Phryganeidae'
 'Hydroptilidae' 'Leptophlebiidae' 'Odontoceridae' 'Polycentropodidae'
 'Metretopodidae' 'Siphlonuridae' 'Ameletidae' 'Uenoidae' 'Glossosomatidae'
 'Leuctridae' 'nan' 'Lepidostomatidae' 'Molannidae' 'Calamoceratidae'
 'Thremmatidae' 'Apataniidae' 'Goeridae' 'Sericostomatidae'
 'Helicopsychidae' 'Apanatiidae' 'None' 'Dipseudopsidae' 'Psychomyiidae'
 'Polymitarcyidae' 'Palingeniidae' 'Potamanthidae' 'Neoephemeridae'] [761 681 297 266 227 215 215 157 150 108 101  96  82  82  79  71  60  55
  53  52  50  49  48  43  40  39  38  36  36  35  33  32  32  29  28  19
  18  13  13  11  10   7   7   6   6   5   5   4   4   3]


In [11]:
n_ind = np.where(df2.family.astype(str) == 'nan')
n_ind

(array([ 698,  699,  700,  701,  702, 1048, 1049, 1050, 1051, 1367, 1368,
        1369, 1705, 1706, 1707, 1713, 1714, 1715]),)

In [12]:
df2.iloc[n_ind].file_name

3648    picture2401.jpg
3649    picture2402.jpg
3650    picture2403.jpg
3651    picture2400.jpg
3652    picture2409.jpg
3998     picture530.jpg
3999     picture531.jpg
4000     picture532.jpg
4001     picture533.jpg
4317     picture785.jpg
4318     picture786.jpg
4319     picture787.jpg
4655     picture789.jpg
4656     picture790.jpg
4657     picture788.jpg
4663     picture782.jpg
4664     picture783.jpg
4665     picture784.jpg
Name: file_name, dtype: object

In [13]:
[np.where(df.file_name == i) for i in df2.iloc[n_ind].file_name]

[(array([3648]),),
 (array([3649]),),
 (array([3650]),),
 (array([3651]),),
 (array([3652]),),
 (array([3998]),),
 (array([3999]),),
 (array([4000]),),
 (array([4001]),),
 (array([4317]),),
 (array([4318]),),
 (array([4319]),),
 (array([4655]),),
 (array([4656]),),
 (array([4657]),),
 (array([4663]),),
 (array([4664]),),
 (array([4665]),)]

In [14]:
#df.loc[df2.iloc[n_ind].index]

In [15]:
df2.drop(df2.iloc[n_ind].index.values,inplace=True)

/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [16]:
df2.family.unique()

array(['Common Burrower Mayflies (Ephemeridae)',
       'Spiny Crawler Mayflies (Ephemerellidae)',
       'Flatheaded Mayflies (Heptageniidae)',
       'Small Minnow Mayflies (Baetidae)',
       'Small Squaregilled Mayflies (Caenidae)',
       'Little Stout Crawler Mayflies (Leptohyphidae)',
       'Pale Burrower Mayflies (Polymitarcyidae)',
       'Riverbed Burrower Mayflies (Palingeniidae)',
       'Hacklegilled Burrower Mayflies (Potamanthidae)',
       'Armored Mayflies (Baetiscidae)',
       'Pronggilled Mayflies (Leptophlebiidae)',
       'Ephemeridae (Hexes and Big Drakes)',
       'Ephemerellidae (Hendricksons, Sulphurs, PMDs, BWOs)',
       'Baetidae (Blue-Winged Olives)',
       'Heptageniidae (March Browns, Cahills, Quill Gordons)',
       'Baetiscidae (Armored Mayflies)', 'Isonychiidae (Slate Drakes)',
       'Ameletidae (Brown Duns)',
       'Leptophlebiidae (Blue Quills and Mahogany Duns)',
       'Siphlonuridae (Gray Drakes)', 'Leptohyphidae (Tricos)',
       'Metretopod

In [17]:
#df2.family = [family_dict[i] for i in df2.family]
family_subset = [family_dict[i] for i in df2.family]
df2.family = family_subset

/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pandas/core/generic.py:3643: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [18]:
family_counts = np.unique(df2.family,return_counts=True)
a = np.flip(np.argsort(family_counts[1]),axis=0)
print(family_counts[0][a],family_counts[1][a])

['Ephemerellidae' 'Heptageniidae' 'Ephemeridae' 'Baetidae' 'Leptohyphidae'
 'Baetiscidae' 'Isonychiidae' 'Caenidae' 'Leptophlebiidae' 'Siphlonuridae'
 'Metretopodidae' 'Ameletidae' 'Polymitarcyidae' 'Potamanthidae'
 'Palingeniidae' 'Neoephemeridae'] [761 681 297 266 227 108  79  53  40  36  36  35   5   4   4   3]


In [19]:
family_list = ['Ephemerellidae', 'Heptageniidae', 'Ephemeridae', 'Baetidae', 'Leptohyphidae']

In [20]:
b = [i in family_list for i in df2.family]

In [21]:
df2.shape

(2635, 13)

In [22]:
df2.loc[b].shape

(2232, 13)

In [23]:
df2 = df2[b]
df2.family.unique()

array(['Ephemeridae', 'Ephemerellidae', 'Heptageniidae', 'Baetidae',
       'Leptohyphidae'], dtype=object)

In [24]:
x = df2.file_name.values
y = df2.family.values

In [25]:
print(x.shape,y.shape)

(2232,) (2232,)


In [324]:
xtrain_val,xtest,ytrain_val,ytest = train_test_split(x,y,test_size = .1)

In [325]:
ytrain_val.shape

(2008,)

In [327]:
xtrain,xval,ytrain,yval = train_test_split(xtrain_val,ytrain_val)

In [328]:
with open('../data/train2/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xtrain,ytrain):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/train2/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [329]:
with open('../data/test2/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xtest,ytest):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/test2/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [330]:
with open('../data/validation2/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xval,yval):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/validation2/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [30]:
dir_l = np.array(os.listdir(path='../data/test'))
dir_l

array(['Ephemeroptera', 'Trichoptera', 'Diptera', 'Plecoptera', 'xy.txt'],
      dtype='<U13')

In [76]:
# dir_l = []
# for d in ['train','validation','test']:
#     for sub_d in ['Ephemeroptera','Trichoptera','Diptera','Plecoptera']:
#         dir_l.append(os.listdir(path='../data/{}/{}'.format(d,sub_d)))

dir_l = []
for d in ['train2','validation2','test2']:
    for sub_d in ['Ephemeridae', 'Ephemerellidae', 'Heptageniidae', 'Baetidae', 'Leptohyphidae']:
        dir_l.append(os.listdir(path='../data/{}/{}'.format(d,sub_d)))

In [77]:
dir_l = np.array(dir_l)
print(len(dir_l))

15


In [78]:
t = 0
for i in range(15):
    print(len(dir_l[i]))
    t = t + len(dir_l[i])
print('total:',t)

196
515
464
174
157
73
166
153
61
49
28
80
64
31
21
total: 2232


In [72]:
np.where(df.partial != 1)[0].shape

(5092,)

In [73]:
np.where(df.ready == 1)[0].shape

(876,)

In [74]:
np.where((df.ruler == 1)|(df.hand_nature == 1))[0].shape

(1502,)

contrast                                 family          file_name  \
33         1    Small Winter Stoneflies (Capniidae)   photo_374894.jpg   
42         1  Rolled-winged Stoneflies (Leuctridae)  photo_1450960.jpg   
58         1  Rolled-winged Stoneflies (Leuctridae)   photo_764312.jpg   
63         0         Spring Stoneflies (Nemouridae)   photo_382533.jpg   
83         0         Spring Stoneflies (Nemouridae)   photo_880212.jpg   

                                         file_path  hand_nature  m_adult  \
33   ../data/bug_guide/plecoptera/photo_374894.jpg            0        0   
42  ../data/bug_guide/plecoptera/photo_1450960.jpg            0        0   
58   ../data/bug_guide/plecoptera/photo_764312.jpg            0        0   
63   ../data/bug_guide/plecoptera/photo_382533.jpg            0        0   
83   ../data/bug_guide/plecoptera/photo_880212.jpg            0        0   

    noisy_background       order  partial  ready  ruler  side_view  
33                 0  Plecoptera        0      0      0          0  
42                 0  Plecoptera        0      0      0          0  
58                 0  Plecoptera        0      0      0          0  
63                 1  Plecoptera        0      0      0          0  
83                 0  Plecoptera        0      0      0          0

In [63]:
df.iloc[np.where(df.partial != 1)[0]].shape

(5092, 13)

In [148]:
'''
RUN ONE:
steps_per_epoch=118
epochs=50
validation_data=validation_generator
validation_steps=6
optimizer='adadelta'
loss='categorical_crossentropy'
metrics=['accuracy']

               precision    recall  f1-score   support

      Diptera       0.79      0.91      0.85       113
Ephemeroptera       0.93      0.86      0.89       214
   Plecoptera       0.73      0.92      0.81        83
  Trichoptera       0.92      0.73      0.82       100

  avg / total       0.87      0.85      0.85       510


'''
df = df.iloc[np.where(df.partial != 1)[0]]

In [75]:
df = df.iloc[np.where((df.ruler != 1)|(df.hand_nature == 1))]

In [80]:
np.unique(df.order,return_counts = True)

(array(['Diptera', 'Ephemeroptera', 'Plecoptera', 'Trichoptera'], dtype=object),
 array([1056, 2494,  809,  927]))

In [94]:
e_ind = np.where(df.order == 'Ephemeroptera')[0]
ind = np.random.choice(e_ind,1000)
ind = np.concatenate((ind, np.where(df.order == 'Diptera')[0]),axis=0)
ind = np.concatenate((ind, np.where(df.order == 'Plecoptera')[0]),axis=0)
ind = np.concatenate((ind, np.where(df.order == 'Trichoptera')[0]),axis=0)

In [95]:
ind.shape

(3792,)

In [99]:
ind

array([3994, 4232, 3316, ..., 2965, 2971, 2972])

In [96]:
df.head()

file_name                                      file_path  ready  \
0   photo_98089.jpg   ../data/bug_guide/plecoptera/photo_98089.jpg      1   
1  photo_255771.jpg  ../data/bug_guide/plecoptera/photo_255771.jpg      1   
2  photo_255991.jpg  ../data/bug_guide/plecoptera/photo_255991.jpg      0   
3  photo_258045.jpg  ../data/bug_guide/plecoptera/photo_258045.jpg      1   
4  photo_654326.jpg  ../data/bug_guide/plecoptera/photo_654326.jpg      0   

   back_view  side_view  ruler  hand_nature  m_adult  contrast  \
0          0          0      0            0        0         0   
1          0          0      0            0        0         0   
2          0          0      0            0        0         0   
3          0          0      0            0        0         0   
4          0          0      0            1        0         0   

   noisy_background  partial       order                                family  
0                 0        0  Plecoptera  Winter Stoneflies (Taeniopterygidae)  
1                 0        0  Plecoptera  Winter Stoneflies (Taeniopterygidae)  
2                 1        0  Plecoptera  Winter Stoneflies (Taeniopterygidae)  
3                 0        0  Plecoptera   Small Winter Stoneflies (Capniidae)  
4                 1        0  Plecoptera        Spring Stoneflies (Nemouridae)

In [114]:
#[df.iloc[np.where(df.file_name == i)[0][0]].order == j for i,j in zip(x,y)]

In [225]:
df.shape

(2232, 13)

In [226]:
x = df.file_name
y = df.order

In [227]:
xtrain_val,xtest,ytrain_val,ytest = train_test_split(x,y,test_size = .1,random_state=77)

In [228]:
xtrain_val.head()

4361      picture18.jpg
3374    picture2245.jpg
4903    picture4090.jpg
3481    picture3078.jpg
3393    picture4539.jpg
Name: file_name, dtype: object

In [117]:
xtrain,xval,ytrain,yval = train_test_split(xtrain_val,ytrain_val,random_state = 42)

In [118]:
with open('../data/train/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xtrain,ytrain):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/train/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [119]:
with open('../data/validation/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xval,yval):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/validation/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [120]:
with open('../data/test/xy.txt','w') as f:
    f.write('file_name,order\n')
    for x,y in zip(xtest,ytest):
        s = '../data/bug_pics/{}'.format(x)
        d = '../data/test/{}/{}'.format(y,x)
        shutil.copy(s,d)
        f.write(x+','+y+'\n')

In [121]:
df_val = pd.read_csv('../data/validation/xy.txt',sep=',')
df_train = pd.read_csv('../data/train/xy.txt',sep=',')
df_test = pd.read_csv('../data/test/xy.txt',sep=',')

In [122]:
print(df_val.shape,df_train.shape,df_test.shape)

(853, 2) (2559, 2) (380, 2)
